#!/bin/bash

# Set the port number.
PORT=${1:-4000}

# Change to area directory.
pushd ../area

NOHUP=true
NICE=true
ulimit -s 1024
if [ -e shutdown.txt ]; then
    rm -f shutdown.txt
fi

if [ ! -p ../system/REQUESTS ]; then
    mkfifo ../system/REQUESTS
fi

I=1000
while [ -e ../log/${I}.log ]; do
	I=$(expr $I + 1)
done
LOGFILE=../log/${I}.log

# Record starting time
date > $LOGFILE
date > ../area/boot.txt

# Record initial charges
# charges >> $logfile

# Run SMAUG.
../src/smaug $PORT > $LOGFILE
#    ../src/smaug >>&! $logfile

    # Record ending charges
    # charges >> $logfile

#    # Delete this out if no adb.
#    if ( -e core ) then
#	    echo '$c' | adb ../src/smaug
#    endif

    # Restart, giving old connections a chance to die.
if [ -e shutdown.txt ]; then
	rm -f shutdown.txt
fi
popd
exit 0
